name: pollino
description: "Your comprehensive Poll App by your side"

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^2.2.0
  http: ^1.5.0
  i18next: ^0.7.3
  json_serializable: ^6.8.0
  routemaster: ^1.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  freezed: ^2.3.0

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
