name: pollino
description: "Your comprehensive Poll App by your side"

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.5.0
  i18next: ^0.7.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  intl_utils: ^2.8.7
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  path_provider: ^2.1.0
  routemaster: ^1.0.1
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.10.2
  # Clean Architecture Dependencies
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.6.4
  injectable: ^2.3.2
  connectivity_plus: ^5.0.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.0
  hive_generator: ^2.0.0
  # Clean Architecture Dev Dependencies
  injectable_generator: ^2.4.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  
  # Internationalization assets
  assets:
    - assets/translations/
